// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrh7ieJTnMKvij_disJ6eRCZX97CXFd8U',
    appId: '1:963278375723:web:8e73a7c7ba189c4dbe136e',
    messagingSenderId: '963278375723',
    projectId: 'tp-vetements',
    authDomain: 'tp-vetements.firebaseapp.com',
    storageBucket: 'tp-vetements.appspot.com',
    measurementId: 'G-YYRJL1RE3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDifbcEWf3XNUfcnYsbJNWh365wgvRqXSY',
    appId: '1:963278375723:android:5e16021785e261aabe136e',
    messagingSenderId: '963278375723',
    projectId: 'tp-vetements',
    storageBucket: 'tp-vetements.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAeswbx3wKsGU5JvLN_3FSpepaDBIi5HQ',
    appId: '1:963278375723:ios:d9aa0ced170fce8dbe136e',
    messagingSenderId: '963278375723',
    projectId: 'tp-vetements',
    storageBucket: 'tp-vetements.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAeswbx3wKsGU5JvLN_3FSpepaDBIi5HQ',
    appId: '1:963278375723:ios:d9aa0ced170fce8dbe136e',
    messagingSenderId: '963278375723',
    projectId: 'tp-vetements',
    storageBucket: 'tp-vetements.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrh7ieJTnMKvij_disJ6eRCZX97CXFd8U',
    appId: '1:963278375723:web:ad00f450f3e23ce4be136e',
    messagingSenderId: '963278375723',
    projectId: 'tp-vetements',
    authDomain: 'tp-vetements.firebaseapp.com',
    storageBucket: 'tp-vetements.appspot.com',
    measurementId: 'G-YZVC7GXXH9',
  );
}
